name: Update Chinese (Traditional) Translation

on:
  push:
    branches:
      - main

jobs:
  update-translation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2

      - name: Install jq and unzip
        run: sudo apt-get install -y jq unzip opencc

      - name: Download pf2e_compendium_chn.zip
        run: wget https://github.com/fvtt-cn/pf2e_compendium_chn/releases/latest/download/pf2e_compendium_chn.zip -O ./.github/pf2e_compendium_chn.zip

      - name: Unzip module.json from pf2e_compendium_chn.zip
        run: unzip -p ./.github/pf2e_compendium_chn.zip 'module.json' >./.github/module.json

      - name: Read version from module.json
        id: read_version
        run: |
          echo "version=$(jq -r '.version' ./.github/module.json)" >> $GITHUB_OUTPUT
          rm ./.github/module.json

      - name: Convert all data by opencc
        run: |
          mkdir -p ./.github/${{ steps.read_version.outputs.version }}
          mkdir -p ./.github/${{ steps.read_version.outputs.version }}old
          unzip ./.github/pf2e_compendium_chn.zip -d ./.github/${{ steps.read_version.outputs.version }
          rm ./.github/${{ steps.read_version.outputs.version }}/babele.js
          opencc -i ./.github/${{ steps.read_version.outputs.version }}old -o ./.github/${{ steps.read_version.outputs.version }} -c s2tw.json
          wget https://raw.githubusercontent.com/hktrpg/pf2e_compendium_zh-tw/main/babele.js -O ./.github/${{ steps.read_version.outputs.version }}/babele.js

      - name: Update version in module.json
        run: jq --arg ver "${{ steps.read_version.outputs.version }}" '.version=$ver' module.json > ./.github/${{ steps.read_version.outputs.version }}/module.json

      - name: Create Artifact
        id: build-zip
        run: zip -j -r ./.github/${{ steps.read_version.outputs.version }}

      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./.github/${{ steps.read_version.outputs.version }}/module.zip, ./.github/${{ steps.read_version.outputs.version }}/module.json"
          tag: ${{ steps.read_version.outputs.version }}
