name: Update Chinese (Traditional) Translation

on:
  push:
    branches:
      - main

jobs:
  update-translation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2

      - name: Install jq and unzip
        run: sudo apt-get install -y jq unzip opencc

      - name: Download pf2e_compendium_chn.zip
        run: wget https://github.com/fvtt-cn/pf2e_compendium_chn/releases/latest/download/pf2e_compendium_chn.zip -O ./.github/pf2e_compendium_chn.zip

      - name: Unzip module.json from pf2e_compendium_chn.zip
        run: unzip -p ./.github/pf2e_compendium_chn.zip 'module.json' >./.github/module.json

      - name: Read version from module.json
        id: read_version
        run: |
          echo "version=$(jq -r '.version' ./.github/module.json)" >> $GITHUB_OUTPUT
          rm ./.github/module.json

      - name: unzip all data
        run: |
          mkdir -p ./.github/${{ steps.read_version.outputs.version }}
          mkdir -p ./.github/${{ steps.read_version.outputs.version }}/npc
          mkdir -p ./.github/${{ steps.read_version.outputs.version }}/compendium
          mkdir -p ./.github/${{ steps.read_version.outputs.version }}-old
          mkdir -p ./.github/${{ steps.read_version.outputs.version }}-tmp
          unzip ./.github/pf2e_compendium_chn.zip -d ./.github/${{ steps.read_version.outputs.version }}-old
          rm ./.github/${{ steps.read_version.outputs.version }}-old/babele.js

      - name: Translate JSON
        run: |
          for file in ./.github/${{ steps.read_version.outputs.version }}-old/compendium/*.json; do
            encoding=$(file -b --mime-encoding "${file}")
            if [ "${encoding}" != "UTF-8" ]; then
              cp "${file}" "./.github/${{ steps.read_version.outputs.version }}-tmp/$(basename "${file}")"
            fi
            opencc -i "${file}" -o "./.github/${{ steps.read_version.outputs.version }}/compendium/$(basename "${file}")" -c s2tw.json
          done
          for file in ./.github/${{ steps.read_version.outputs.version }}-old/npc/*.json; do
            encoding=$(file -b --mime-encoding "${file}")
            if [ "${encoding}" != "UTF-8" ]; then
              cp "${file}" "./.github/${{ steps.read_version.outputs.version }}-tmp/$(basename "${file}")"
            fi
            opencc -i "${file}" -o "./.github/${{ steps.read_version.outputs.version }}/npc/$(basename "${file}")" -c s2tw.json
          done

      - name: Update version in module.json
        run: |
          wget https://raw.githubusercontent.com/hktrpg/pf2e_compendium_zh-tw/main/babele.js -O ./.github/${{ steps.read_version.outputs.version }}/babele.js
          jq --arg ver "${{ steps.read_version.outputs.version }}" '.version=$ver' module.json > ./.github/${{ steps.read_version.outputs.version }}/module.json

      - name: Create Artifact
        id: build-zip
        run: (cd ./.github/${{ steps.read_version.outputs.version}} &&  zip -r module.zip "compendium/" "npc/" .)

      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./.github/${{ steps.read_version.outputs.version }}/module.zip, ./.github/${{ steps.read_version.outputs.version }}/module.json"
          tag: ${{ steps.read_version.outputs.version }}
